### PR TITLE
implement getorderbook and getticker

### PR DESCRIPTION
**Pull request by jasonwee**

### CODE REVIEW

**Comment by jasonwee** [comment]
hmm.. not sure why codecov failed. Did I miss any tests?

**Comment by CCob** [comment]
It's because one of the branches on `getOrderBook` is not tested - "buy/sell" vs "any".  How about an enum as the type argument, with "buy", "sell" and "both" as the options?  That way it will simplify `getOrderBook` and the user is forced to pick a valid option.  Codecov shouldn't complain then either.

**Comment by CCob** [comment]
Other than that, looks good to me

**Comment by CCob** [comment]
Feel free to add yourself as the author too on your new files.

**Comment by jasonwee** [comment]
okay, now all good. :) could you please make a release because i use this lib?

**Comment by CCob** [comment]
I will hopefully get some time to kick off a Maven repo build later

**Pull request merged**
